#!/usr/bin/env python

# WS client example

import asyncio
import websockets
import json
from contextlib import suppress


async def hello():
    data_set = {"arr" : "image"}
    json_dumps = json.dumps(data_set)
    j_out = json.loads(json_dumps)
    uri = "ws://0.0.0.0:8080"
    async with websockets.connect(uri) as websocket:
        with open('./AreaFSPL.json') as f: 
           data = json.loads(f.read())
        # print(json.dumps(data, indent=4, sort_keys=True))
        await websocket.send(json.dumps(data))

        while True:
            greeting = await websocket.recv()
            data = json.loads(greeting)
            if data["type"] == "partial":
                # j_out.update(data["result"])
                print(json.dumps(data, indent=4, sort_keys=True)) 
            

async def main():
    asyncio.ensure_future(hello())  # fire and forget
    await asyncio.sleep(1)

if __name__ == '__main__':
    loop = asyncio.get_event_loop()
    loop.run_until_complete(main())

    # Let's also cancel all running tasks:
    pending = asyncio.Task.all_tasks()
    for task in pending:
        task.cancel()
        # Now we should await task to execute it's cancellation.
        # Cancelled task raises asyncio.CancelledError that we can suppress:
        with suppress(asyncio.CancelledError):
            loop.run_until_complete(task)


# asyncio.get_event_loop().run_until_complete(hello())
