language: bash

# See https://github.com/amaiorano/vectrexy/blob/master/.travis.yml
# for ideas on installing vcpkg

matrix:
  include:
    # macOS
    # - os: osx
    #   env:
    #     - HOMEBREW_NO_AUTO_UPDATE=1
    #   compiler: clang
    #   script:
    #     - brew install redis
    #     - brew services start redis
    #     - brew install mbedtls
    #     - python test/run.py
    #     - make ws

    Linux
    - os: linux
      dist: bionic
      before_install:
        - sudo apt-get install -y libmbedtls-dev
        - sudo apt-get install -y redis-server
      script: 
      - python test/run.py
      #  - make ws
      env:
        - CC=gcc
        - CXX=g++

    # Clang + Linux disabled for now
    # - os: linux
    #   dist: xenial
    #   script: python test/run.py
    #   env:
    #     - CC=clang 
    #     - CXX=clang++

    # Windows
    # - os: windows
    #   env:
    #     - CMAKE_PATH="/c/Program Files/CMake/bin"
    #   script: 
    #     - cd third_party/zlib
    #     - cmake .
    #     - cmake --build . --target install
    #     - cd ../..
    #     # - cd third_party/mbedtls
    #     # - cmake .
    #     # - cmake --build . --target install
    #     # - cd ../..
    #     - export PATH=$CMAKE_PATH:$PATH
    #     - cd test
    #     - cmake .
    #     - cmake --build --parallel .
    #     - ixwebsocket_unittest.exe
    #     # - python test/run.py
